name: Add Script
description: Add a Script to The RoboFont Mechanic Script Database.
title: "[Add Script]: "
labels: ["add-script"]
assignees:
  - typemytype
  - ryanbugden
body:
  - type: markdown
    attributes:
      value: |

        Add a Script to The RoboFont Mechanic Script Database.

        Thanks for submitting!

  - type: input
    id: name
    attributes:
      label: Title
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Script Link
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: developer
    attributes:
      label: Developer
    validations:
      required: true

  - type: input
    id: developerURL
    attributes:
      label: Developer URL
    validations:
      required: true

  - type: dropdown
    id: tags
    attributes:
      label: Tags
      description: Select one or more tags.
      multiple: true
      options:
        - accented glyphs
        - anchors
        - appearance
        - character set
        - clipboard
        - components
        - contours
        - designspace
        - diacritics
        - drawing
        - editing tools
        - extension management
        - ezui
        - figures
        - font dimensions
        - font generation
        - font lib
        - font overview
        - fractions
        - glyph generator
        - glyph view
        - glyphs
        - groups
        - guidelines
        - inspector
        - interpolation
        - italics
        - kerning
        - layers
        - menu
        - merz
        - mojo
        - notes
        - notifications
        - observers
        - pens
        - points
        - safe mode
        - saving
        - scripting
        - selection
        - space center
        - spacing
        - subscriber
        - tabular figures
        - transform
        - unicode
        - user interface
        - vanilla
    validations:
      required: true

