name: Add Script
description: Add a Script to The RoboFont Mechanic Script Database.
title: "[Add Script]: "
labels: ["add-script"]
assignees:
  - typemytype
  - ryanbugden
body:
  - type: markdown
    attributes:
      value: |

        Add a Script to The RoboFont Mechanic Script Database.

        Thanks for submitting!

  - type: input
    id: name
    attributes:
      label: Name
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Script Link
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: developer
    attributes:
      label: Developer
    validations:
      required: true

  - type: input
    id: developerURL
    attributes:
      label: Developer URL
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: Tags
      description: A comma separated list of tags.
    validations:
      required: true